### ISSUE TITLE
[BE] Flyway를 적용한다.

### ISSUE THREAD

**Issue by asebn1** [woowacourse-teams/2022-nae-pyeon#190]
## 기능 상세
- Flyway를 적용한다.
  - [x] [BE] `BaseEntity`를 제외한 V1 버전에 Flyway를 적용한다.
  - [x] [BE] 생성일자, 수정일자 필드가 추가된 V2 버전 Flyway를 적용한다.

**Comment by kth990303** [comment]
## 현재는 Flyway 적용 불가능
### 원인
- 현재 #88 , #185 이슈가 PR 머지로 close 됨. 이 때 테이블은 변경이 되지 않았고 엔티티(BaseEntity, color)만 변경이 돼버림. 따라서 빌드가 되지 않음.
 
### 해결 방법
1. DB EC2 -> MySQL 접속해서 Table을 직접 수정해준 후, 빌드를 돌린 후에 flyway를 적용
2. `BaseEntity`를 주석처리한 후에, `color` 필드만 table 직접 수정 후, 빌드를 돌린 후에 flyway 적용 -> `BaseEntity` flyway에 추가 
  - `color` 필드도 주석처리할 경우, 테스트 쪽을 전부 주석처리하거나 변경해야 됨.
  - `color` 필드는 직접 DB에 추가하기 쉬우나, `BaseEntity`는 생성일자, 수정일자 쪽이라 시간 이슈가 발생할 수 있음.

**Comment by kth990303** [comment]
## 트러블 슈팅
### 원인
![image](https://user-images.githubusercontent.com/57135043/181411286-d49e8324-f35c-4682-b9ea-a61a9d586a70.png)
현재 test DB가 MySQL이 아닌 H2 여서 아래 이슈 발생
1. H2 database를 1.4.200 버전으로 설정해주지 않으면 위 에러 발생
2. H2 문법에 맞지 않는 `engine=InnoDB default charset utf8mb4;` 부분 때문에 위 에러 발생

### 해결방법
1. 버전 설정 후, H2 DB 명세 따로 생성
2. 로컬 test DB를 MySQL로 변경

![image](https://user-images.githubusercontent.com/57135043/181411662-975eb776-619f-431b-a144-582a05196b72.png)
위 빨간 박스에 해당되는 부분이 실행할 때 출력돼야 함.
* * *
 ### 원인
![image](https://user-images.githubusercontent.com/57135043/181411472-c343ecd7-d8ff-4e72-9332-8508c016b2b3.png)
flyway-schema-db에 init.sql 스키마 적용이 안됨. (실행만 됨)

### 해결방법
1. 오타가 있었다. `v1__init.sql`이 아니고 `V1__init.sql`

![image](https://user-images.githubusercontent.com/57135043/181411625-8da059fa-0376-452b-bf69-53d65551ad02.png)
위와 같이 되면 올바르게 생성된 것.

**Comment by kth990303** [comment]
## Flyway + MySQL 마이그레이션 에러 이슈
- MySQL로 업그레이드했을 때, 테스트 격리가 안되는 현상 발생
  - Flyway 문제가 아닌, MySQL로 인한 문제였음. MySQL로 변경 시, db에 들어가지 않은 데이터들이 일부 들어가는 현상 발생. 이 부분에 대해서는 좀 더 원인 파악을 해봐야될 듯.

### 해결방안
- `로컬(local)`, `배포(prod)`에서는 Flyway + MySQL
- `테스트(test)`용 yml 파일 생성 후, `Flyway enable = false`로 등록
  - build가 통과했다는 것 자체가 entity와 db table의 간극이 존재하지 않는다는 것이므로 test에서까지 flyway를 적용할 필요는 없을 듯함.
  - flyway는 배포 서버의 MySQL 테이블을 이용한다. 따라서 flyway의 schema는 MySQL 환경이다. 하지만 현재 사용중인 H2 테스트 환경에서는 개발된 api가 정상적으로 작동하는지 테스트하는 것이 목적이고, db에 의존하지는 않는다. 즉, flyway schema (MySQL)를 따라갈 필요가 없기 때문에 flyway schema를 사용하지 않고 테스트해도 무방하다.
