### ISSUE TITLE
[BE] Flyway 적용이 안되는 버그를 해결한다.

### ISSUE THREAD

**Issue by kth990303** [woowacourse-teams/2022-nae-pyeon#210]
## 기능 상세
- 애플리케이션을 실행할 때, `DBMigrate` 문구가 나오지 않고, `flyway_schema_history` 테이블이 생성되지 않는다.

**Comment by asebn1** [comment]
수정사항
1. 테스트에서 flyway 사용하지 않음을 명시적으로 변경
2. 의존성을 추가한다(flyway) : develop에 머지될 때 꼬여서 삭제된듯하다.
