### ISSUE TITLE
[BE] 마이페이지에서 유저가 작성한 메시지 목록을 조회하는 기능을 구현한다.

### ISSUE THREAD

**Issue by kth990303** [woowacourse-teams/2022-nae-pyeon#217]

**Comment by kth990303** [comment]
## 내가 작성한 메시지 목록을 얻어오는 방법으로 어떤 것이 좋을까?
현재 내가 작성한 메시지를 얻어오는 api 응답으로는 `Message` 도메인에 들어있는 정보들뿐만 아니라 상당히 많은 정보들이 필요하다.
```javascript
messages: [
  {
	  id: 1,
	  rollingpaperId: 1,
	  rollingpaperTitle: '소피아의 생일을 축하해',
	  teamId: 3,
	  teamName: '우테코 4기',
	  to: '소피아',
	  content: '소피아야 생일 축하해~ 축카추카추 소피아야 생일 축하해~ 축카추카추',
	  color: 'red'
  },
  {
	  id: 2,
	  rollingpaperId: 2,
	  rollingpaperTitle: '소피아의 생일을 축하해',
	  teamId: 3,
          teamName: '우테코 4기',
	  to: '소피아',
	  content: '소피아야 생일 축하해~ 축카추카추 소피아야 생일 축하해~ 축카추카추',
	  color: 'yellow'
  },
]
```
위 문제를 해결하는 방법은 두 가지가 있다.
1. Repository에서 응답 api에서 요구하는 필드값들을 포함하는 DTO를 반환한다. 그러기 위해 SQL 네이티브 쿼리를 여러 번 join해서 작성한다.  
2. Repository에서 도메인을 반환하고, Service에서 Repository 메서드를 요구되는 필드가 포함된 도메인 수만큼 호출한다.

**Comment by asebn1** [comment]
페치조인을 사용하지 않고, BatchSize를 설정해서 진행하는 건 어떠신가요?
### 페치조인의 한계

- 별칭을 줄 수 없다.
- 둘 이상의 컬렉션은 페치조인 할 수 없다.
- `컬렉션을 페치 조인하면 페이징 API를 사용할 수 없다.`
    - 1:1, N:1은 페치조인해도 페이징 가능하다.
    - 1:N의 경우 데이터가 추가되기 때문에 사용할 수 없다.
    - 해결방법은? `페치조인을 사용하지 않고`, `BatchSize를 설정`한다.
    
    ```java
    @BatchSize(size=100)
    @OneToMany(mappedBy="team")
    private List<Member> members = new ArrayList<>();
    ```
