### ISSUE TITLE
[BE] 내가 쓴 메시지 조회 방식 개선

### ISSUE THREAD

**Issue by yxxnghwan** [woowacourse-teams/2022-nae-pyeon#492]
## 기능 상세
- 현재 날 세타 조인 상태
- 연관관계를 추가로 정의해서 Team에서 TeamParticipation을 서치할 수 있도록 변경
- 이후 다시 해당 로직을 고민해본다. 
- 현재처럼 전부 조인이 아니라 해당 API를 다시 짠다면 어떻게 짤거고 연관관계가 맺어진 상태에서 발생하는 문제를 어떻게 해결할지 다시 적용해보기

**Comment by kth990303** [comment]
## 솔루션 1.

### Team 엔티티에 List<TeamParticipation> 양방향 연관관계 추가

문제점

1. 모임을 생성한 사람 역시 팀에 가입돼야 함 → Team 생성 시 TeamParticipation 편의 메서드로 가입시켜주기 
    - `new Team(name, description, ... ,teamParticipation)` 생성자로 모임을 생성할 때 TeamParticipation도 넣어주자 → `new TeamParticipation(team, member, nickname)` 으로 TeamParticipation을 생성하고 이를 team 생성자에 넣어주려 하니 아직 Team이 만들어지지 않음 → 순환참조!
    - 반대로 `new TeamParticipation()` → `new Team()`으로 해도 마찬가지이다.
    - 생성자 시점에서 가입시키지 않고 서비스에서 별도로 따로 넣어주면 안되냐? → 양방향으로 하는 이점이 무엇이 있을까?
        - 이렇게 하면 TeamService에서 팀을 저장할 때도, 팀을 찾을 때도 결국은 따로 성능적으로 나아지는 부분은 딱히 없음.
2. message 쪽에서 닉네임을 찾아올 때 성능(join, N+1 등) 이슈의 근본적인 해결책이 되지 않는다.
    - 하나의 Team은 여러 개의 TeamParticipation을 가질 수 있다.
    
    <img width="679" alt="image" src="https://user-images.githubusercontent.com/57135043/193181292-327d75a9-9184-44fa-8b3a-1e5682e7161b.png">
    
    - 메시지 작성자의 닉네임을 찾을 때 `message` - `rollingpaper` - `team` - `teamParticipation` 과 연관관계는 생겨서 `theta join`으로 인한 `cross join`은 해결될 수 있을 것으로 보인다.
        - 하지만 특정 teamParticipation의 nickname은 어떻게 찾을 것인가?
            - 하나의 Team이 여러 TeamParticipation을 가지기 때문에 특정 TeamParticipation을 조회하려면 다시 where절과 join절의 복잡한 쿼리가 들어가게 된다.
            - 또한, 결국 여러 find 작업이 들어가서 성능적으로 이슈가 생긴다.
        - `getTeamParticipation().getNickname()` 으로 인한 N+1 문제는 어떻게 해결할 것인가?
            - 결국 다시 복잡한 쿼리?

**Comment by kth990303** [comment]
## 솔루션 2. (가장 좋다고 생각되는 솔루션)

### Message 엔티티에 TeamParticipation `@ManyToOne` 단방향 연관관계 추가

- Message에 TeamParticipation이 존재하면 바로 닉네임을 알 수 있고, TeamParticipation이 존재하면 쿼리 상으로 Author(Member)과 nickname을 빠르게 얻어올 수 있음.

![image](https://user-images.githubusercontent.com/57135043/193181386-9108e875-5b76-4538-86ed-709dc8b1f171.png)


- 그렇다면 TeamParticipation을 저장하기 위해 member은 저장할 수 있다 치지만 team, nickname은 어디서 얻어올까?

→ team은 메시지 작성 시에 내편 uri에 이미 teamId가 있어서 찾아올 수 있음.

![image](https://user-images.githubusercontent.com/57135043/193181484-e1bf9188-9561-4e4a-a6ff-a0f40b14a4d6.png)

![image](https://user-images.githubusercontent.com/57135043/193181506-151d19fb-d72b-4fde-a63f-0d180946302f.png)

- 이 부분의 uri을 `/api/v1/teams/{teamId}/rollingpapers/{rollingpaperId}/messages`로 바꾼다면 teamId를 얻어오는 건 충분히 가능 (이미 내편 uri에선 teamId/rollingpaperId 식으로 돼있음)
- 대신 프론트에서 메시지 관련한 요청 uri을 수정해줘야될듯

→ nickname은 teamParticipationRepository의 findByTeamIdAndMemberId로 성능 저하 없이 바로 찾아올 수 있음.

## 메시지에 teamParticipation이 존재한다면 아래 메서드들 모두 개선 가능

### 1. 본인이 작성한 메시지 조회

![image](https://user-images.githubusercontent.com/57135043/193181526-03d5d766-58ab-4dc1-ac24-2b27bc3aaec5.png)

![image](https://user-images.githubusercontent.com/57135043/193181545-624da24e-e898-464e-aa2d-4fca7548b2a3.png)


- 복잡한 쿼리의 주범.
    - message와 TeamParticipation이 연관관계를 맺으면 join할 필요 전혀 없어짐.
    - 본인이 작성한 메시지 메서드에 필요한 DTO에서 요구하는 정보들이 message와 연관관계가 맺어진 TeamParticipation, Rollingpaper에서 모두 존재하는 정보들임

### 2. 메시지 단건 조회 (쓰이는지 잘 모르겠음)

![image](https://user-images.githubusercontent.com/57135043/193181571-4fb3e791-f7d3-452c-8fd3-b8d661976545.png)

- Team 정보를 가져오기 위해 필요하지도 않은 롤링페이퍼를 꺼내쓰고, 거기서 Team을 꺼냄.
- `MessageResponseDto`의 nickname을 가져오기 위해 위처럼 찾은 teamId, authorId를 이용하여 다시 find 작업을 하는 중.
    - TeamParticipation이 연관관계로 있다면 불필요한 Rollingpaper, Team들을 꺼내지 않아도 됨.

---

- `MessageResponseDto`의 nickname을 가져오기 위해 rollingpaper.getTeam().getId()를 하는 과정에서 N+1 문제가 발생한다.
- `TeamParticipation`를 가져온다 해도 message.getTeamParticipation().getNickname()을 할 때  n+1이 발생하지 않느냐 → querydsl를 이용하여 teamParticipationRepository.findNicknameByAuthorId 를 생성하면 N+1 문제없이도 가능

```sql
queryFactory.select(teamParticipation.nickname)
							.from(teamParticipation)
							.leftJoin(message.teamParticipation, teamParticipation)
							.fetchJoin()
							.where(isAuthorId(authorId)) // memberId 같을 때
							.fetch()
```

### 3. 메시지 전체 조회 (롤링페이퍼 단건 조회 시에 사용되는 메서드임)

![image](https://user-images.githubusercontent.com/57135043/193181607-f03fd2de-6f8e-4bc1-80ac-00a7633a2a37.png)

- message.getAuthor().getId() (N+1 맞고) 의 값으로 TeamParticipationRepository.findNickname 하는 중
    - message.getParticipation().getNickname() → N+1
    - querydsl를 이용하여 teamParticipationRepository.findNicknameByAuthorId 를 생성하면 N+1 문제없이 가능
    
    ```sql
    queryFactory.select(teamParticipation.nickname)
    							.from(teamParticipation)
    							.leftJoin(message.teamParticipation, teamParticipation)
    							.fetchJoin()
    							.where(isAuthorId(authorId)) // memberId 같을 때
    							.fetch()
    ```
    

### 객체지향적인 관점으로 봤을 때 괜찮은가?

- 특정 회원이 팀이 가입했을 때 해당 `닉네임`을 가진 캐릭터 상태로 메시지를 작성한다. 따라서 Member 객체가 메시지를 작성한다는 관점보다 TeamParticipation(해당 팀에 가입된 닉네임을 가지는 객체)이 메시지를 작성한다는 관점이 오히려 적합할 수 있다.

### 개인 롤링페이퍼에선 어떻게 할 것인가?

- 개인 롤링페이퍼에선 별도로 개인을 위한 Team을 하나씩 생성하는 것 외엔 특별한 방법이 떠오르지 않는다.
  - 불필요한 데이터를 N개 추가로 넣어야된다는 단점  

### 생각해볼만한 거리

1. teamParticipation을 연관관계로 가진다면 author (Member)을 연관관계로 가질 필요가 있을까?
2. saveMessage에서는 findRollingpaper, findMember 작업을 해줬었다. 만약 teamParticipation을 연관관계로 가진다면 findTeam, findMember, findTeamParticipationByTeamIdAndMemberId 로 조금 느려질 수도 있다. 대신 조회 관련 기능들의 성능과 복잡도가 많이 개선될 듯하다.

**Comment by kth990303** [comment]
## 솔루션 3.

### Message 엔티티에 authorNickname 컬럼 추가

→ 개인롤링페이퍼에서는 본인 이름을 넣어줌.

장점

- 위 메서드들의 성능 저하는 대체로 Nickname을 얻기 위함임. 따라서 메시지 작성자의 nickname을 컬럼으로 들고 있는 것도 좋을 듯.
- message.getTeamParticipation.getNickname()을 하는 경우 N+1 문제 유발 → authorNickname을 들고 있으면 N+1 문제 발생 안함. (fetch join할 필요도 없음)

단점

- 본인이 작성한 메시지 조회쿼리 시 여전히 theta join이 필요함. 이렇게 되면 크로스 조인으로 나가기 때문에 성능상으로 치명적임.
    - 다만, 닉네임을 얻어오기 위해 teamParticipation을 조인한 것이라 추측되기 때문에 theta join 자체가 필요없어지지 않을까? 이렇다면 성능상으로도 개선된다.

![image](https://user-images.githubusercontent.com/57135043/193181700-311d5a88-0020-47c3-8f2e-48e106a28e2b.png)

**Comment by kth990303** [comment]
## 솔루션 4.

### Rollingpaper 엔티티에 addresseeNickname 컬럼 추가

→ 개인롤링페이퍼에서는 team.getName()을 넣어줌.

장점

- 본인이 작성한 메시지의 case-when절이 사라지게 됨.
- teamParcitipation cross join 안해줘도 됨. 본인이 작성한 메시지 조회 성능 향상 기대

단점

- 본인이 작성한 메시지 조회는 쿼리를 1번 날리는 기능이었음. 그렇지만 가독성은 똥.
- 이렇게 개선하게 되면 가독성은 훨씬 좋아지지만 오히려 성능 자체는 느려질 수 있음.

### 생각해볼만한 거리

- Rollingpaper에서 Member(수신인)을 가질 필요가 있을가? member_id를 가져도 될듯? N+1도 사라지게된다.

**Comment by kth990303** [comment]
## 솔루션 4. -> DB 제3정규화 위반 (nickname 변경 시에 teamParticipation 닉네임뿐만 아니라 롤링페이퍼 닉네임도 자동으로 변경해줘야 함 -> 객체로 연관관계 외래키 설정해 줘야 함)

### Rollingpaper 엔티티에 addresseeNickname 컬럼 추가

→ 개인롤링페이퍼에서는 team.getName()을 넣어줌.

장점

- 본인이 작성한 메시지의 case-when절이 사라지게 됨.
- teamParcitipation cross join 안해줘도 됨. 본인이 작성한 메시지 조회 성능 향상 기대

단점

- 본인이 작성한 메시지 조회는 쿼리를 1번 날리는 기능이었음. 그렇지만 가독성은 똥.
- 이렇게 개선하게 되면 가독성은 훨씬 좋아지지만 오히려 성능 자체는 느려질 수 있음.

### 생각해볼만한 거리

- Rollingpaper에서 Member(수신인)을 가질 필요가 있을가? member_id를 가져도 될듯? N+1도 사라지게된다.

**Comment by yxxnghwan** [comment]
# 솔루션 6.

롤링페이퍼 종류별로 수퍼 서브 타입으로 재설계

'''
Rollingpaper extends BaseEntity
{
  Recipient
}

MemberRollingpaper extends Rollingpaper
{
  TeamParitication
}

TeamRollingpaper extends Rollingpaper
{
  Team
}

PersonalRollingpaper extends Rollingpaper
{
  Member
}
'''
