### ISSUE TITLE
[FE] 웹 접근성을 개선한다.

### ISSUE THREAD

**Issue by jin7969** [woowacourse-teams/2022-nae-pyeon#520]
## 피드백

- ⭐️ 작성하기 버튼이 “버튼”으로만 읽어줌, 어떤 기능인지 읽어주면 좋겠다
  - alt, aria-label 등 작성하기
- 포스트잇 색상이 선택이 안됨
  - ??
- 포스트잇 색상 읽어주기
  - aria-label 작성하기
- 포스트잇 색상에 선택영역 숨기기
  - aria-hidden 으로 스크린 리더는 읽지만 사용자는 보이지 않게 한다 
- 저장시 작성되었음을 알려주면 좋겠다
  - 스낵바에 role 추가 ex) "메시지 작성 완료"
- 익명 선택 안됨 - 웹
  - ??
- 포스트잇에서 저장, 취소 버튼으로 자연스레 넘어가지 않는다 - 모바일

**Comment by soyi47** [comment]
- [ ] 아이콘 버튼 alt 추가하기(뒤로가기, 메시지 작성하기, 좋아요, 메시지 수정, 메시지 삭제)
- [ ] MessageColorPicker가 MessageTextArea보다 먼저 위치하기
- [ ] MessageColorPicker의 색상 읽어주기
- [ ] MessageColorPicker 포커스 영역 지정하기
- [ ] MessageForm의 저장, 취소 버튼 순서를 취소 다음 저장으로 바꾸기
