### ISSUE TITLE
[BE] 로그인 API와 인증이 필요한 API별 인증처리를 구현한다.

### ISSUE THREAD

**Issue by yxxnghwan** [woowacourse-teams/2022-nae-pyeon#61]
## 기능 상세
- email과 password를 받아 jwt를 반환하는 로그인 API를 구현
- 인증이 필요한 API요청시 토큰을 검사하도록 인증 로직 추가 (Interceptor와 ArgumentResolver 사용)
- 인증 실패시 발생하는 예외 정의 및 명세

**Comment by kth990303** [comment]
auth 패키지는 naepyeon 패키지 외부에 생성함.
- 기존에 존재하는 
- 인증 부분에서 oauth 기능이 추가된다면, 해당 부분은 NaePyeon 관련 기능이 아닌 외부 라이브러리 (ex. 카카오 로그인, 깃허브 로그인)를 사용하는 것이므로 naepyeon package 내가 아닌, 외부에 생성하는 것이 맞지 않을까?
